spring:
  main:
    allow-circular-references: true #Problemas con version a spring 2.6 se restablece el comportamiento de spring 2.5
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/CalentanaDB?createDatabaseIfNotExist=true
    username : ceiba
    password: ceiba
server:
  port: 8081